In [1]:
import pandas as pd
import re
import html

In [4]:
comments_df = pd.read_csv("D:/Social media Assignment 2/comments.csv")

comments_df.head()

,video_id,video_title,author,comment_text,comment_published_at,comment_like_count
0,laZpTO7IFtA,Is 67 just brain rot?,@ExoticNibbles2,Nothing makes me feel older then watching a 15...,2025-10-14T22:24:09Z,7902
1,laZpTO7IFtA,Is 67 just brain rot?,@andrewbunnell7576,6 x 7 = 42 The answer to Life the Universe and...,2025-10-13T20:12:09Z,7692
2,laZpTO7IFtA,Is 67 just brain rot?,@ColinPaddock,All I know is 6 is afraid of 7.,2025-10-14T06:39:54Z,6194
3,laZpTO7IFtA,Is 67 just brain rot?,@codahighland,Having COMPLETELY no context for it before thi...,2025-12-10T16:03:28Z,121
4,laZpTO7IFtA,Is 67 just brain rot?,@yoberry.,"The next time my kid says ""6-7"", I'm going to ...",2025-10-18T07:29:08Z,2084

In [6]:
print("Original dataset shape:", comments_df.shape)

comments_df.info()

Original dataset shape: (6249, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6249 entries, 0 to 6248
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   video_id              6249 non-null   object
 1   video_title           6249 non-null   object
 2   author                6249 non-null   object
 3   comment_text          6248 non-null   object
 4   comment_published_at  6249 non-null   object
 5   comment_like_count    6249 non-null   int64
dtypes: int64(1), object(5)
memory usage: 293.1+ KB

In [8]:
def clean_comment(text):
    if pd.isna(text):
        return None

    text = str(text)

    # Convert HTML entities like &amp; to &
    text = html.unescape(text)

    # Remove URLs only
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)

    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)

    # Lowercase text
    text = text.lower()

    # Remove excessive whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


def is_invalid_comment(text):
    if pd.isna(text):
        return True

    text = str(text).strip().lower()

    invalid_values = [
        "",
        "[deleted]",
        "[removed]",
        "deleted",
        "removed",
        "nan",
        "none"
    ]

    return text in invalid_values

In [10]:
comments_cleaned = comments_df[
    ~comments_df["comment_text"].apply(is_invalid_comment)
].copy()

comments_cleaned = comments_cleaned.drop_duplicates(
    subset=["video_id", "author", "comment_text"]
)

print("Shape after removing invalid/duplicate comments:", comments_cleaned.shape)

Shape after removing invalid/duplicate comments: (6243, 6)

In [12]:
comments_cleaned["clean_comment"] = comments_cleaned["comment_text"].apply(clean_comment)

comments_cleaned = comments_cleaned[
    ~comments_cleaned["clean_comment"].apply(is_invalid_comment)
].copy()

comments_cleaned.head()

,video_id,video_title,author,comment_text,comment_published_at,comment_like_count,clean_comment
0,laZpTO7IFtA,Is 67 just brain rot?,@ExoticNibbles2,Nothing makes me feel older then watching a 15...,2025-10-14T22:24:09Z,7902,nothing makes me feel older then watching a 15...
1,laZpTO7IFtA,Is 67 just brain rot?,@andrewbunnell7576,6 x 7 = 42 The answer to Life the Universe and...,2025-10-13T20:12:09Z,7692,6 x 7 = 42 the answer to life the universe and...
2,laZpTO7IFtA,Is 67 just brain rot?,@ColinPaddock,All I know is 6 is afraid of 7.,2025-10-14T06:39:54Z,6194,all i know is 6 is afraid of 7.
3,laZpTO7IFtA,Is 67 just brain rot?,@codahighland,Having COMPLETELY no context for it before thi...,2025-12-10T16:03:28Z,121,having completely no context for it before thi...
4,laZpTO7IFtA,Is 67 just brain rot?,@yoberry.,"The next time my kid says ""6-7"", I'm going to ...",2025-10-18T07:29:08Z,2084,"the next time my kid says ""6-7"", i'm going to ..."

In [14]:
comments_cleaned["comment_length_chars"] = comments_cleaned["clean_comment"].apply(len)

comments_cleaned["comment_length_words"] = comments_cleaned["clean_comment"].apply(
    lambda x: len(str(x).split())
)

comments_cleaned.head()

,video_id,video_title,author,comment_text,comment_published_at,comment_like_count,clean_comment,comment_length_chars,comment_length_words
0,laZpTO7IFtA,Is 67 just brain rot?,@ExoticNibbles2,Nothing makes me feel older then watching a 15...,2025-10-14T22:24:09Z,7902,nothing makes me feel older then watching a 15...,109,20
1,laZpTO7IFtA,Is 67 just brain rot?,@andrewbunnell7576,6 x 7 = 42 The answer to Life the Universe and...,2025-10-13T20:12:09Z,7692,6 x 7 = 42 the answer to life the universe and...,57,13
2,laZpTO7IFtA,Is 67 just brain rot?,@ColinPaddock,All I know is 6 is afraid of 7.,2025-10-14T06:39:54Z,6194,all i know is 6 is afraid of 7.,31,9
3,laZpTO7IFtA,Is 67 just brain rot?,@codahighland,Having COMPLETELY no context for it before thi...,2025-12-10T16:03:28Z,121,having completely no context for it before thi...,93,18
4,laZpTO7IFtA,Is 67 just brain rot?,@yoberry.,"The next time my kid says ""6-7"", I'm going to ...",2025-10-18T07:29:08Z,2084,"the next time my kid says ""6-7"", i'm going to ...",88,18

In [16]:
for comment in comments_cleaned["clean_comment"].head(10):
    print(comment)
    print("-" * 80)

nothing makes me feel older then watching a 15 minute video breaking down slang the young kids use these days
--------------------------------------------------------------------------------
6 x 7 = 42 the answer to life the universe and everything
--------------------------------------------------------------------------------
all i know is 6 is afraid of 7.
--------------------------------------------------------------------------------
having completely no context for it before this video, i thought it was a solo version of 69.
--------------------------------------------------------------------------------
the next time my kid says "6-7", i'm going to punish him by making him watch this video.
--------------------------------------------------------------------------------
if someone says “6-7” i’m gonna say “10-4”
--------------------------------------------------------------------------------
so it’s the linguistic equivalent of somebody getting a teardrop tattoo under their eye cause they thought it was cute
--------------------------------------------------------------------------------
a switch is a modification to a semiautomatic firearm to make it fully automatic; which would cause it to make a sound like “brrt”.
--------------------------------------------------------------------------------
"you know what's funnier than 24? 25! 🤣🤣🤣" - spongebob that's what this amounts to.
--------------------------------------------------------------------------------
as a millenial, all this makes me think is, i just lost the game
--------------------------------------------------------------------------------

In [18]:
comments_cleaned.to_csv("comments_cleaned.csv", index=False, encoding="utf-8")

print("Saved as comments_cleaned.csv")
print("Final cleaned dataset shape:", comments_cleaned.shape)

Saved as comments_cleaned.csv
Final cleaned dataset shape: (6241, 9)